# Generated by Django 5.2.3 on 2026-01-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('ASPIRANTE', 'Aspirante a Crédito'), ('ANALISTA', 'Analista de Crédito'), ('DIRECTOR', 'Director')], max_length=10),
        ),
    ]
