# Generated by Django 5.2.3 on 2025-06-23 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0005_alter_documento_nombre_documento_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='solicitud_actual',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_analista_asignado', to='creditos.solicitudcredito'),
        ),
    ]
