# Generated by Django 5.2.3 on 2025-06-22 23:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo_cliente', models.CharField(max_length=255, verbose_name='Nombre completo del cliente')),
                ('cedula_cliente', models.CharField(max_length=20, unique=True, verbose_name='Cédula del cliente')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento del cliente')),
                ('telefono_cliente', models.CharField(max_length=20, verbose_name='Teléfono del cliente')),
                ('email_cliente', models.EmailField(max_length=254, verbose_name='Email del cliente')),
                ('direccion_cliente', models.CharField(max_length=255, verbose_name='Dirección del cliente')),
                ('actividad_economica', models.CharField(max_length=100, verbose_name='Actividad económica')),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto solicitado')),
                ('plazo_meses', models.PositiveIntegerField(verbose_name='Plazo en meses')),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_EVALUACION', 'En Evaluación Automática'), ('RECHAZADO_AUTO', 'Rechazado Automáticamente'), ('PEND_DOCUMENTOS', 'Pendiente Carga Documentos Iniciales'), ('EN_ASIGNACION', 'En Espera de Asignación de Analista'), ('EN_ANALISIS', 'En Análisis por Analista'), ('PREAPROBADO', 'Pre-Aprobado por Analista'), ('RECHAZADO_ANALISTA', 'Rechazado por Analista'), ('PEND_DOCS_ADICIONALES', 'Pendiente Documentos Adicionales'), ('EN_VALIDACION_DOCS', 'En Validación de Documentos'), ('DOCS_CORRECCION', 'Documentos en Corrección'), ('PEND_APROB_DIRECTOR', 'Pendiente Aprobación Director'), ('APROBADO', 'Aprobado Final'), ('RECHAZADO_DIRECTOR', 'Rechazado por Director')], default='NUEVO', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observacion_centrales_riesgo', models.TextField(blank=True, null=True, verbose_name='Observación Centrales de Riesgo')),
                ('observacion_llamada_cliente', models.TextField(blank=True, null=True, verbose_name='Observación Llamada con Cliente')),
                ('observacion_referencias', models.TextField(blank=True, null=True, verbose_name='Observación de Referencias')),
                ('analista_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Analista Asignado')),
                ('asesor_comercial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Asesor Comercial')),
            ],
            options={
                'verbose_name': 'Solicitud de Crédito',
                'verbose_name_plural': 'Solicitudes de Crédito',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('numero_contacto', models.CharField(max_length=20)),
                ('parentesco', models.CharField(help_text='Ej: Amigo, Primo, Padre, etc.', max_length=50)),
                ('tipo', models.CharField(choices=[('PERSONAL', 'Personal'), ('FAMILIAR', 'Familiar')], max_length=10)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='creditos.solicitudcredito')),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_nuevo', models.CharField(max_length=30)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, help_text='Razón del cambio de estado, si aplica.', null=True)),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='creditos.solicitudcredito')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historiales de Estado',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(help_text='Ej: Cédula, Certificado Laboral', max_length=100)),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/%d/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('ok_analista', models.BooleanField(default=False, verbose_name='Documento Validado (OK)')),
                ('observacion_correccion', models.TextField(blank=True, null=True, verbose_name='Observación para Corrección')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='creditos.solicitudcredito')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
