# Generated by Django 5.2.3 on 2025-06-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcredito',
            name='observacion_analisis_documentos',
        ),
        migrations.RemoveField(
            model_name='solicitudcredito',
            name='recomendacion_sistema_texto',
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='barrio_residencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barrio de Residencia'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='ciudad_residencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad de Residencia'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='departamento_residencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento de Residencia'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='direccion_residencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de Residencia'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='es_tipo_0',
            field=models.BooleanField(null=True, verbose_name='¿Es tipo 0?'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('DIVORCIADO', 'Divorciado/a'), ('UNION_LIBRE', 'Unión Libre')], max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='estrato',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Estrato'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='gastos_financieros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Gastos Financieros Confirmados'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='gastos_personales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Gastos Personales Reportados'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='huellas_consulta',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Número de huellas de consulta'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='mora_otros_mayor_500k',
            field=models.BooleanField(null=True, verbose_name='¿Mora otros productos > $500.000?'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='mora_telco_mayor_300k',
            field=models.BooleanField(null=True, verbose_name='¿Mora Telco > $300.000?'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='num_aportantes',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2')], default=1, null=True, verbose_name='Número de Aportantes'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='otros_gastos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Otros Gastos Mensuales'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='personas_a_cargo',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('+5', 'Más de 5')], max_length=10, null=True, verbose_name='Personas a cargo'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='sexo',
            field=models.CharField(blank=True, choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer')], max_length=10, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='tiene_procesos_judiciales',
            field=models.BooleanField(null=True, verbose_name='¿Tiene procesos judiciales?'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='tipo_vivienda',
            field=models.CharField(blank=True, choices=[('PROPIA', 'Propia'), ('FAMILIAR', 'Familiar'), ('ARRIENDO', 'En Arriendo')], max_length=20, null=True, verbose_name='Tipo de Vivienda'),
        ),
    ]
