# Generated by Django 5.2.3 on 2025-06-23 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudcredito',
            old_name='cedula_cliente',
            new_name='cedula',
        ),
        migrations.RenameField(
            model_name='solicitudcredito',
            old_name='nombre_completo_cliente',
            new_name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='solicitudcredito',
            name='actividad_economica',
        ),
        migrations.RemoveField(
            model_name='solicitudcredito',
            name='direccion_cliente',
        ),
        migrations.RemoveField(
            model_name='solicitudcredito',
            name='email_cliente',
        ),
        migrations.RemoveField(
            model_name='solicitudcredito',
            name='monto_solicitado',
        ),
        migrations.RemoveField(
            model_name='solicitudcredito',
            name='plazo_meses',
        ),
        migrations.RemoveField(
            model_name='solicitudcredito',
            name='telefono_cliente',
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='actividad_economica_restringida',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Actividad Económica (si es restringida)'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='causal_no_sujeto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Causal de no sujeto a crédito'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='es_tipo_0',
            field=models.BooleanField(null=True, verbose_name='¿Es tipo 0?'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='fecha_expedicion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de expedición de la cédula'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='huellas_consulta',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de huellas de consulta'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='ingresos_totales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ingresos Totales (COP)'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='mora_otros_mayor_500k',
            field=models.BooleanField(null=True, verbose_name='¿Mora otros productos > $500.000?'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='mora_telco_mayor_300k',
            field=models.BooleanField(null=True, verbose_name='¿Mora Telco > $300.000?'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='ocupacion',
            field=models.CharField(blank=True, choices=[('EMPLEADO', 'Empleado'), ('INDEPENDIENTE', 'Independiente'), ('PENSIONADO', 'Pensionado')], max_length=20, null=True, verbose_name='Ocupación'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='personas_a_cargo',
            field=models.CharField(blank=True, choices=[('1-5', 'Entre 1 y 5'), ('+5', 'Más de 5')], max_length=10, null=True, verbose_name='Personas a cargo'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='tiene_procesos_judiciales',
            field=models.BooleanField(null=True, verbose_name='¿Tiene procesos judiciales?'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='tiene_vivienda_propia',
            field=models.BooleanField(default=False, verbose_name='¿Tiene vivienda propia?'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='analista_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='asesor_comercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_EVALUACION', 'En Evaluación Automática'), ('RECHAZADO_AUTO', 'Rechazado Automáticamente'), ('PEND_DOCUMENTOS', 'Pasa a Estudio (Pend. Documentos)'), ('EN_ASIGNACION', 'En Espera de Asignación de Analista'), ('EN_ANALISIS', 'En Análisis por Analista'), ('PREAPROBADO', 'Pre-Aprobado por Analista'), ('RECHAZADO_ANALISTA', 'Rechazado por Analista'), ('PEND_DOCS_ADICIONALES', 'Pendiente Documentos Adicionales'), ('EN_VALIDACION_DOCS', 'En Validación de Documentos'), ('DOCS_CORRECCION', 'Documentos en Corrección'), ('PEND_APROB_DIRECTOR', 'Pendiente Aprobación Director'), ('APROBADO', 'Aprobado Final'), ('RECHAZADO_DIRECTOR', 'Rechazado por Director')], default='NUEVO', max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
