# Generated by Django 5.2.3 on 2025-06-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0002_rename_cedula_cliente_solicitudcredito_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='personas_a_cargo',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('+5', 'Más de 5')], max_length=10, null=True, verbose_name='Personas a cargo'),
        ),
    ]
