# Generated by Django 5.2.3 on 2025-06-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0003_alter_solicitudcredito_personas_a_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_EVALUACION', 'En Evaluación Automática'), ('RECHAZADO_AUTO', 'Rechazado Automáticamente'), ('EN_ASIGNACION', 'En Espera de Asignación de Analista'), ('EN_ANALISIS', 'En Análisis por Analista'), ('PREAPROBADO', 'Pre-Aprobado por Analista'), ('RECHAZADO_ANALISTA', 'Rechazado por Analista'), ('PEND_DOCS_ADICIONALES', 'Pendiente Documentos Adicionales'), ('EN_VALIDACION_DOCS', 'En Validación de Documentos'), ('DOCS_CORRECCION', 'Documentos en Corrección'), ('PEND_APROB_DIRECTOR', 'Pendiente Aprobación Director'), ('APROBADO', 'Aprobado Final'), ('RECHAZADO_DIRECTOR', 'Rechazado por Director')], default='NUEVO', max_length=30),
        ),
    ]
