# Generated by Django 5.2.3 on 2025-06-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0003_solicitudcredito_observacion_analisis_documentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='recomendacion_sistema_aprobada',
            field=models.BooleanField(null=True, verbose_name='¿Sistema recomienda aprobar?'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='recomendacion_sistema_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Texto de recomendación del sistema'),
        ),
    ]
