# Generated by Django 5.2.3 on 2025-06-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0004_alter_solicitudcredito_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='nombre_documento',
            field=models.CharField(choices=[('CEDULA', 'Cédula'), ('DECLARACION_RENTA', 'Declaración de Renta'), ('CERTIFICADO_LABORAL', 'Certificado Laboral'), ('AUTORIZACION_CONSULTA', 'Autorización de Consulta a Centrales')], help_text='Ej: Cédula, Certificado Laboral', max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_EVALUACION', 'En Evaluación Automática'), ('RECHAZADO_AUTO', 'Rechazado Automáticamente'), ('PEND_DOCUMENTOS', 'Pendiente Carga Documentos Iniciales'), ('EN_ASIGNACION', 'En Espera de Asignación de Analista'), ('EN_ANALISIS', 'En Análisis por Analista'), ('PREAPROBADO', 'Pre-Aprobado por Analista'), ('RECHAZADO_ANALISTA', 'Rechazado por Analista'), ('PEND_DOCS_ADICIONALES', 'Pendiente Documentos Adicionales'), ('EN_VALIDACION_DOCS', 'En Validación de Documentos'), ('DOCS_CORRECCION', 'Documentos en Corrección'), ('PEND_APROB_DIRECTOR', 'Pendiente Aprobación Director'), ('APROBADO', 'Aprobado Final'), ('RECHAZADO_DIRECTOR', 'Rechazado por Director')], default='NUEVO', max_length=30),
        ),
    ]
