# Generated by Django 5.2.3 on 2025-06-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0004_solicitudcredito_recomendacion_sistema_aprobada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='ok_analista',
            field=models.BooleanField(default=True, verbose_name='Documento Validado (OK)'),
        ),
    ]
