# Generated by Django 5.2.3 on 2025-06-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0005_alter_documento_ok_analista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='ok_analista',
            field=models.BooleanField(default=False, verbose_name='Documento Validado (OK)'),
        ),
    ]
