# Generated by Django 5.2.3 on 2025-06-24 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0005_alter_documento_nombre_documento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='subido_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='observacion_analisis_documentos',
            field=models.TextField(blank=True, null=True, verbose_name='Observación del Análisis de Documentos'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nombre_documento',
            field=models.CharField(choices=[('Documentos del Asesor', [('CEDULA', 'Cédula'), ('DECLARACION_RENTA', 'Declaración de Renta'), ('CERTIFICADO_LABORAL', 'Certificado Laboral'), ('AUTORIZACION_CONSULTA', 'Autorización de Consulta a Centrales')]), ('Documentos de Análisis', [('HISTORIAL_CREDITO', 'Historial de Crédito (PDF)'), ('PROCESOS_JUDICIALES', 'Pantallazo de Procesos Judiciales'), ('ADRESS', 'Pantallazo ADRESS'), ('CONTRALORIA', 'Antecedentes en Contraloría (PDF)'), ('PROCURADURIA', 'Antecedentes en Procuraduría (Pantallazo)'), ('OTRAS_CONSULTAS', 'Otras Consultas (Puesto de Votación, Sisbén)')])], max_length=100),
        ),
    ]
