# Generated by Django 5.2.3 on 2025-06-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0006_documento_subido_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='recomendacion_sistema_aprobada',
            field=models.BooleanField(null=True, verbose_name='¿Sistema recomienda aprobar?'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='recomendacion_sistema_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Texto de recomendación del sistema'),
        ),
    ]
