# Generated by Django 5.2.3 on 2025-06-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0006_alter_documento_ok_analista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='nombre_documento',
            field=models.CharField(choices=[('Documentos del Asesor', [('CEDULA', 'Cédula'), ('DECLARACION_RENTA', 'Declaración de Renta'), ('CERTIFICADO_LABORAL', 'Certificado Laboral'), ('AUTORIZACION_CONSULTA', 'Autorización de Consulta a Centrales')]), ('Documentos de Análisis', [('HISTORIAL_CREDITO', 'Historial de Crédito (PDF)'), ('PROCESOS_JUDICIALES', 'Pantallazo de Procesos Judiciales'), ('ADRESS', 'Pantallazo ADRESS'), ('CONTRALORIA', 'Antecedentes en Contraloría (PDF)'), ('PROCURADURIA', 'Antecedentes en Procuraduría (Pantallazo)'), ('OTRAS_CONSULTAS', 'Otras Consultas (Puesto de Votación, Sisbén)')]), ('Documentos de Cierre', [('PAGARE', 'Pagaré'), ('CARTA_INSTRUCCIONES', 'Carta de Instrucciones'), ('POLIZA_SEGURO', 'Póliza de Seguro'), ('FORMATO_VINCULACION', 'Formato de Vinculación')])], max_length=100),
        ),
    ]
