# Generated by Django 5.2.3 on 2025-06-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0007_solicitudcredito_recomendacion_sistema_aprobada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='barrio_residencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barrio de Residencia'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='ciudad_residencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad de Residencia'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='departamento_residencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento de Residencia'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='direccion_residencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de Residencia'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('DIVORCIADO', 'Divorciado/a'), ('UNION_LIBRE', 'Unión Libre')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='estrato',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Estrato'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='gastos_financieros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Gastos Financieros Confirmados'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='gastos_personales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Gastos Personales Mensuales'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='sexo',
            field=models.CharField(blank=True, choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='tipo_vivienda',
            field=models.CharField(blank=True, choices=[('PROPIA', 'Propia'), ('FAMILIAR', 'Familiar'), ('ARRIENDO', 'En Arriendo')], max_length=20, null=True),
        ),
    ]
