# Generated by Django 5.2.3 on 2025-06-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0008_solicitudcredito_barrio_residencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='aplicar_cuota_inicial',
            field=models.BooleanField(default=False, verbose_name='¿Aplicar cálculo de cuota inicial? (10%)'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='capacidad_pago_calculada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Capacidad de Pago Calculada'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='empero_capacidad',
            field=models.BooleanField(default=False, verbose_name='¿Aplica empeoramiento de capacidad? (-2%)'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='mejora_capacidad',
            field=models.BooleanField(default=False, verbose_name='¿Aplica mejora de capacidad? (+5%)'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='num_aportantes',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Número de Aportantes al Ingreso'),
        ),
    ]
