# Generated by Django 5.2.3 on 2025-06-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0009_solicitudcredito_aplicar_cuota_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('DIVORCIADO', 'Divorciado/a'), ('UNION_LIBRE', 'Unión Libre')], max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='gastos_personales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Gastos Personales Reportados'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='num_aportantes',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2')], default=1, verbose_name='Número de Aportantes'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='sexo',
            field=models.CharField(blank=True, choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer')], max_length=10, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='tipo_vivienda',
            field=models.CharField(blank=True, choices=[('PROPIA', 'Propia'), ('FAMILIAR', 'Familiar'), ('ARRIENDO', 'En Arriendo')], max_length=20, null=True, verbose_name='Tipo de Vivienda'),
        ),
    ]
