# Generated by Django 5.2.3 on 2025-06-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0010_alter_solicitudcredito_estado_civil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcredito',
            name='aplicar_cuota_inicial',
        ),
        migrations.RemoveField(
            model_name='solicitudcredito',
            name='empero_capacidad',
        ),
        migrations.RemoveField(
            model_name='solicitudcredito',
            name='gastos_personales',
        ),
        migrations.RemoveField(
            model_name='solicitudcredito',
            name='mejora_capacidad',
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='otros_gastos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Otros Gastos Mensuales'),
        ),
    ]
