# Generated by Django 5.2.3 on 2025-06-25 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0011_remove_solicitudcredito_aplicar_cuota_inicial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcredito',
            name='otros_gastos',
        ),
    ]
