# Generated by Django 5.2.3 on 2025-07-04 21:04

import creditos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0011_alter_solicitudcredito_monto_solicitado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to='documentos/%Y/%m/%d/', validators=[creditos.models.validate_file_extension_and_size]),
        ),
    ]
