# Generated by Django 5.2.3 on 2025-06-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0012_remove_solicitudcredito_otros_gastos'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='gastos_personales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Gastos Personales Reportados'),
        ),
    ]
