# Generated by Django 5.2.3 on 2025-06-27 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula del cliente')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre completo del cliente')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('fecha_expedicion', models.DateField(verbose_name='Fecha de expedición de la cédula')),
                ('ocupacion', models.CharField(choices=[('EMPLEADO', 'Empleado'), ('INDEPENDIENTE', 'Independiente'), ('PENSIONADO', 'Pensionado')], max_length=20, verbose_name='Ocupación')),
                ('ingresos_totales', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ingresos Totales (Reportados por Asesor)')),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Solicitado por Cliente')),
                ('plazo_solicitado', models.PositiveSmallIntegerField(verbose_name='Plazo Solicitado por Cliente (meses)')),
                ('tipo_vivienda', models.CharField(choices=[('PROPIA', 'Propia'), ('FAMILIAR', 'Familiar'), ('ARRIENDO', 'En Arriendo')], max_length=20, verbose_name='Tipo de Vivienda')),
                ('personas_a_cargo', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('+5', 'Más de 5')], max_length=10, verbose_name='Personas a cargo')),
                ('direccion_residencia', models.CharField(max_length=255, verbose_name='Dirección de Residencia')),
                ('ciudad_residencia', models.CharField(max_length=100, verbose_name='Ciudad de Residencia')),
                ('departamento_residencia', models.CharField(max_length=100, verbose_name='Departamento de Residencia')),
                ('barrio_residencia', models.CharField(max_length=100, verbose_name='Barrio de Residencia')),
                ('estrato', models.PositiveSmallIntegerField(verbose_name='Estrato')),
                ('estado_civil', models.CharField(choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('DIVORCIADO', 'Divorciado/a'), ('UNION_LIBRE', 'Unión Libre')], max_length=20, verbose_name='Estado Civil')),
                ('sexo', models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer')], max_length=10, verbose_name='Sexo')),
                ('gastos_personales', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Gastos Personales Reportados')),
                ('gastos_financieros', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Gastos Financieros Confirmados')),
                ('otros_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otros Gastos Mensuales')),
                ('num_aportantes', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2')], default=1, verbose_name='Número de Aportantes')),
                ('mora_telco_mayor_300k', models.BooleanField(verbose_name='¿Mora Telco > $300.000?')),
                ('mora_otros_mayor_500k', models.BooleanField(verbose_name='¿Mora otros productos > $500.000?')),
                ('es_tipo_0', models.BooleanField(verbose_name='¿Es tipo 0?')),
                ('huellas_consulta', models.PositiveIntegerField(default=0, verbose_name='Número de huellas de consulta')),
                ('tiene_procesos_judiciales', models.BooleanField(verbose_name='¿Tiene procesos judiciales?')),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('RECHAZADO_AUTO', 'Rechazado Automáticamente'), ('PEND_DOCUMENTOS', 'Pendiente Carga Documentos Iniciales'), ('EN_ASIGNACION', 'En Espera de Asignación de Analista'), ('EN_ANALISIS', 'En Análisis por Analista'), ('PREAPROBADO', 'Pre-Aprobado por Analista'), ('RECHAZADO_ANALISTA', 'Rechazado por Analista'), ('PEND_DOCS_ADICIONALES', 'Pendiente Documentos Adicionales'), ('EN_VALIDACION_DOCS', 'En Validación de Documentos'), ('DOCS_CORRECCION', 'Documentos en Corrección'), ('PEND_APROB_DIRECTOR', 'Pendiente Aprobación Director'), ('APROBADO', 'Aprobado Final'), ('RECHAZADO_DIRECTOR', 'Rechazado por Director')], default='NUEVO', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('observacion_analisis_documentos', models.TextField(blank=True, null=True, verbose_name='Observación del Análisis de Documentos')),
                ('observacion_oferta_final', models.TextField(blank=True, null=True, verbose_name='Justificación de la Oferta Definitiva')),
                ('recomendacion_sistema_texto', models.TextField(blank=True, null=True, verbose_name='Texto de recomendación del sistema')),
                ('capacidad_pago_calculada', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Capacidad de Pago Calculada')),
                ('plazo_oferta', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Plazo de la Oferta (meses)')),
                ('monto_aprobado_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Máximo Aprobado')),
                ('analista_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL)),
                ('asesor_comercial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Crédito',
                'verbose_name_plural': 'Solicitudes de Crédito',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('numero_contacto', models.CharField(max_length=20)),
                ('parentesco', models.CharField(help_text='Ej: Amigo, Primo, Padre, etc.', max_length=50)),
                ('tipo', models.CharField(choices=[('PERSONAL', 'Personal'), ('FAMILIAR', 'Familiar')], max_length=10)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='creditos.solicitudcredito')),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_nuevo', models.CharField(max_length=30)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, help_text='Razón del cambio de estado, si aplica.', null=True)),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='creditos.solicitudcredito')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historiales de Estado',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(choices=[('Documentos del Asesor', [('CEDULA', 'Cédula'), ('DECLARACION_RENTA', 'Declaración de Renta'), ('CERTIFICADO_LABORAL', 'Certificado Laboral'), ('AUTORIZACION_CONSULTA', 'Autorización de Consulta a Centrales')]), ('Documentos de Análisis', [('HISTORIAL_CREDITO', 'Historial de Crédito (PDF)'), ('PROCESOS_JUDICIALES', 'Pantallazo de Procesos Judiciales'), ('ADRESS', 'Pantallazo ADRESS'), ('CONTRALORIA', 'Antecedentes en Contraloría (PDF)'), ('PROCURADURIA', 'Antecedentes en Procuraduría (Pantallazo)'), ('OTRAS_CONSULTAS', 'Otras Consultas (Puesto de Votación, Sisbén)')])], max_length=100)),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/%d/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('ok_analista', models.BooleanField(default=False, verbose_name='Documento Validado (OK)')),
                ('observacion_correccion', models.TextField(blank=True, null=True, verbose_name='Observación para Corrección')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='creditos.solicitudcredito')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
