# Generated by Django 5.2.3 on 2025-06-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0002_remove_solicitudcredito_observacion_analisis_documentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='observacion_analisis_documentos',
            field=models.TextField(blank=True, null=True, verbose_name='Observación del Análisis de Documentos'),
        ),
    ]
