# Generated by Django 5.2.3 on 2025-06-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0007_alter_documento_nombre_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='ok_analista',
            field=models.BooleanField(default=True, verbose_name='Documento Validado (OK)'),
        ),
    ]
