# Generated by Django 5.2.3 on 2025-06-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0008_alter_documento_ok_analista'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosGlobales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smlv', models.DecimalField(decimal_places=2, default=1300000, max_digits=10, verbose_name='Salario Mínimo Legal Vigente (SMLV)')),
                ('tasa_interes_mensual', models.DecimalField(decimal_places=4, default=0.023, max_digits=5, verbose_name='Tasa de Interés Mensual (Ej: 0.023 para 2.3%)')),
                ('porcentaje_seguro', models.DecimalField(decimal_places=4, default=0.0025, max_digits=5, verbose_name='Porcentaje del Seguro sobre el Monto')),
                ('porcentaje_fgs', models.DecimalField(decimal_places=4, default=0.0025, max_digits=5, verbose_name='Porcentaje del Fondo de Garantías (FGS)')),
            ],
            options={
                'verbose_name': 'Parámetro Global',
                'verbose_name_plural': 'Parámetros Globales',
            },
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('RECHAZADO_AUTO', 'Rechazado Automáticamente'), ('PEND_DOCUMENTOS', 'Pendiente Carga Documentos Iniciales'), ('EN_ASIGNACION', 'En Espera de Asignación de Analista'), ('EN_ANALISIS', 'En Análisis por Analista'), ('PREAPROBADO', 'Pre-Aprobado por Analista'), ('RECHAZADO_ANALISTA', 'Rechazado por Analista'), ('DOCS_FINALES_CORRECCION', 'En Corrección de Documentos Finales'), ('PEND_DOCS_ADICIONALES', 'Pendiente Documentos Adicionales'), ('EN_VALIDACION_DOCS', 'En Validación de Documentos'), ('DOCS_CORRECCION', 'Documentos en Corrección'), ('PEND_APROB_DIRECTOR', 'Pendiente Aprobación Director'), ('APROBADO', 'Aprobado Final'), ('RECHAZADO_DIRECTOR', 'Rechazado por Director')], default='NUEVO', max_length=30),
        ),
    ]
