# Generated by Django 5.2.3 on 2025-07-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0009_parametrosglobales_alter_solicitudcredito_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='observacion_referencias',
            field=models.TextField(blank=True, null=True, verbose_name='Observación de Referencias'),
        ),
    ]
