# Generated by Django 5.2.3 on 2025-07-04 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0010_solicitudcredito_observacion_referencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='monto_solicitado',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(500000, 'El monto solicitado debe ser de al menos $500,000.')], verbose_name='Monto Solicitado por Cliente'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='plazo_solicitado',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(6, 'El plazo mínimo es de 6 meses.')], verbose_name='Plazo Solicitado por Cliente (meses)'),
        ),
    ]
