# Generated by Django 5.2.3 on 2026-01-14 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0012_alter_documento_archivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcredito',
            name='asesor_comercial',
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='aspirante',
            field=models.ForeignKey(blank=True, help_text='Usuario vinculado después de registro', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_como_aspirante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='email_aspirante',
            field=models.EmailField(default='', max_length=255, verbose_name='Email del Aspirante'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='telefono_aspirante',
            field=models.CharField(default='', max_length=20, verbose_name='Telefono del Aspirante'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='token_expiracion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiración del Token'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='token_registro',
            field=models.CharField(blank=True, help_text='Token temporal para completar registro post-aprobación', max_length=64, null=True, unique=True, verbose_name='Token de Registro'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nombre_documento',
            field=models.CharField(choices=[('Documentos del Aspirante', [('CEDULA', 'Cédula'), ('DECLARACION_RENTA', 'Declaración de Renta'), ('CERTIFICADO_LABORAL', 'Certificado Laboral'), ('AUTORIZACION_CONSULTA', 'Autorización de Consulta a Centrales')]), ('Documentos de Análisis', [('HISTORIAL_CREDITO', 'Historial de Crédito (PDF)'), ('PROCESOS_JUDICIALES', 'Pantallazo de Procesos Judiciales'), ('ADRESS', 'Pantallazo ADRESS'), ('CONTRALORIA', 'Antecedentes en Contraloría (PDF)'), ('PROCURADURIA', 'Antecedentes en Procuraduría (Pantallazo)'), ('OTRAS_CONSULTAS', 'Otras Consultas (Puesto de Votación, Sisbén)')]), ('Documentos de Cierre', [('PAGARE', 'Pagaré'), ('CARTA_INSTRUCCIONES', 'Carta de Instrucciones'), ('POLIZA_SEGURO', 'Póliza de Seguro'), ('FORMATO_VINCULACION', 'Formato de Vinculación')])], max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='ingresos_totales',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ingresos Totales'),
        ),
        migrations.CreateModel(
            name='NotificacionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BIENVENIDA', 'Bienvenida'), ('CAMBIO_ESTADO', 'Cambio de Estado'), ('DOCS_RECHAZADOS', 'Documentos Rechazados'), ('APROBACION_FINAL', 'Aprobación Final'), ('RECHAZO', 'Rechazo')], max_length=30, verbose_name='Tipo de Notificación')),
                ('email_destino', models.EmailField(max_length=254, verbose_name='Email de Destino')),
                ('asunto', models.CharField(max_length=255, verbose_name='Asunto')),
                ('contenido', models.TextField(blank=True, null=True, verbose_name='Contenido del Email')),
                ('enviado', models.BooleanField(default=False, verbose_name='¿Enviado?')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('error_mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_email', to='creditos.solicitudcredito')),
            ],
            options={
                'verbose_name': 'Notificación de Email',
                'verbose_name_plural': 'Notificaciones de Email',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
