# Generated by Django 5.2.3 on 2026-02-03 13:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0013_remove_solicitudcredito_asesor_comercial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionemail',
            name='tipo',
            field=models.CharField(choices=[('PREAPROBACION', 'Pre-aprobacion Inicial'), ('BIENVENIDA', 'Bienvenida'), ('EN_ESPERA', 'Solicitud en Espera'), ('ASIGNADO', 'Asignado a Analista'), ('CAMBIO_ESTADO', 'Cambio de Estado'), ('DOCS_RECHAZADOS', 'Documentos Rechazados'), ('APROBACION_FINAL', 'Aprobación Final'), ('RECHAZO', 'Rechazo por Director'), ('RECHAZO_MOTOR', 'Rechazo Automatico')], max_length=30, verbose_name='Tipo de Notificación'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='cedula',
            field=models.CharField(max_length=20, unique=True, verbose_name='Numero de Cedula'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='fecha_expedicion',
            field=models.DateField(verbose_name='Fecha de Expedicion de la Cedula'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='ingresos_totales',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ingresos Mensuales'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='monto_solicitado',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(500000, 'El monto solicitado debe ser de al menos $500,000.')], verbose_name='Monto Solicitado'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='nombre_completo',
            field=models.CharField(max_length=255, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='ocupacion',
            field=models.CharField(choices=[('EMPLEADO', 'Empleado'), ('INDEPENDIENTE', 'Independiente'), ('PENSIONADO', 'Pensionado')], max_length=20, verbose_name='Ocupacion'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='plazo_solicitado',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(6, 'El plazo minimo es de 6 meses.')], verbose_name='Plazo Solicitado (meses)'),
        ),
        migrations.CreateModel(
            name='ConsultaDataCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('tipo_consulta', models.CharField(choices=[('HPN', 'Historia de Crédito'), ('RECONOCER', 'Reconocer Master')], max_length=20, verbose_name='Tipo de Consulta')),
                ('estado_consulta', models.CharField(choices=[('EXITO', 'Consulta exitosa'), ('ERROR', 'Error en consulta'), ('SIN_DATOS', 'Sin datos en central'), ('NO_ENCONTRADO', 'Identificación no encontrada')], default='EXITO', max_length=20, verbose_name='Estado')),
                ('codigo_respuesta', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código de Respuesta')),
                ('mensaje_respuesta', models.TextField(blank=True, null=True, verbose_name='Mensaje de Respuesta')),
                ('advance_score', models.IntegerField(blank=True, null=True, verbose_name='Advance Score (Z0)')),
                ('score_descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción Score')),
                ('quanto_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Quanto (O4)')),
                ('total_obligaciones', models.IntegerField(blank=True, null=True, verbose_name='Total Obligaciones')),
                ('obligaciones_al_dia', models.IntegerField(blank=True, null=True, verbose_name='Obligaciones al Día')),
                ('obligaciones_mora', models.IntegerField(blank=True, null=True, verbose_name='Obligaciones en Mora')),
                ('saldo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Saldo Total')),
                ('saldo_mora', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Saldo en Mora')),
                ('cuota_mensual_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cuota Mensual Total')),
                ('mora_telco', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Mora Telco')),
                ('mora_sector_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Mora Sector Real')),
                ('mora_sector_financiero', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Mora Sector Financiero')),
                ('huellas_ultimos_6_meses', models.IntegerField(blank=True, null=True, verbose_name='Huellas últimos 6 meses')),
                ('vector_comportamiento', models.JSONField(blank=True, null=True, verbose_name='Vector de Comportamiento (24m)')),
                ('reconocer_ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad (Reconocer)')),
                ('reconocer_departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento (Reconocer)')),
                ('reconocer_direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección (Reconocer)')),
                ('reconocer_estrato', models.CharField(blank=True, max_length=10, null=True, verbose_name='Estrato (Reconocer)')),
                ('reconocer_telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono (Reconocer)')),
                ('reconocer_celular', models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular (Reconocer)')),
                ('reconocer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email (Reconocer)')),
                ('respuesta_cruda', models.JSONField(blank=True, null=True, verbose_name='Respuesta JSON Completa')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_datacredito', to='creditos.solicitudcredito')),
            ],
            options={
                'verbose_name': 'Consulta DataCrédito',
                'verbose_name_plural': 'Consultas DataCrédito',
                'ordering': ['-fecha_consulta'],
            },
        ),
    ]
