# Generated by Django 5.2.3 on 2026-03-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0014_alter_notificacionemail_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultadatacredito',
            name='codigo_respuesta',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Código de Respuesta'),
        ),
    ]
