# Generated by Django 5.2.3 on 2026-03-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0015_alter_consultadatacredito_codigo_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='convenio',
            field=models.CharField(blank=True, help_text='Convenio o alianza comercial asociada a esta solicitud', max_length=100, null=True, verbose_name='Convenio'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('RECHAZADO_AUTO', 'Rechazado Automáticamente'), ('PEND_DOCUMENTOS', 'Pendiente Carga Documentos Iniciales'), ('EN_ASIGNACION', 'En Espera de Asignación de Analista'), ('EN_ANALISIS', 'En Análisis por Analista'), ('PREAPROBADO', 'Pre-Aprobado por Analista'), ('RECHAZADO_ANALISTA', 'Rechazado por Analista'), ('DOCS_FINALES_CORRECCION', 'En Corrección de Documentos Finales'), ('PEND_DOCS_ADICIONALES', 'Pendiente Documentos Adicionales'), ('EN_VALIDACION_DOCS', 'En Validación de Documentos'), ('DOCS_CORRECCION', 'Documentos en Corrección'), ('PEND_APROB_DIRECTOR', 'Pendiente Aprobación Director'), ('APROBADO', 'Aprobado Final'), ('RECHAZADO_DIRECTOR', 'Rechazado por Director'), ('DESEMBOLSADO', 'Desembolsado')], default='NUEVO', max_length=30),
        ),
    ]
