"""
Django settings for core_credito project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'debug_toolbar',
    # 'axes',  # Desactivado temporalmente
    'usuarios.apps.UsuariosConfig',
    'creditos.apps.CreditosConfig',
    
]


AUTHENTICATION_BACKENDS = [
    # AxesBackend desactivado temporalmente
    # 'axes.backends.AxesBackend',

    # El backend por defecto de Django debe mantenerse.
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'axes.middleware.AxesMiddleware',  # Desactivado temporalmente
]

ROOT_URLCONF = 'core_credito.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core_credito.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
LOGIN_URL = 'login'


# --- CONFIGURACIÓN DE TIMEOUT DE SESIÓN ---
# Duración de la sesión en segundos (ej: 15 minutos * 60 segundos = 900)
SESSION_COOKIE_AGE = 900


# Le decimos a Django que resetee el contador de inactividad con cada petición.
# Esto significa que mientras el usuario esté activo, su sesión no expirará.
SESSION_SAVE_EVERY_REQUEST = True

INTERNAL_IPS = ['127.0.0.1']

# --- CONFIGURACIÓN DE EMAIL ---
# En desarrollo, los emails se imprimen en consola
# En produccion, configurar variables en .env
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='Core de Credito <noreply@corecredito.com>')

# URL base del sitio (para emails enviados sin request)
SITE_URL = config('SITE_URL', default='http://localhost:8000')

# ==============================================================================
# CONFIGURACIÓN DATACREDITO
# ==============================================================================

# --- HPN REST API (Historia de Crédito + Advance Score + Quanto) ---
DATACREDITO_HPN = {
    'ENABLED': config('DATACREDITO_HPN_ENABLED', default=False, cast=bool),
    'TOKEN_URL': config('DATACREDITO_HPN_TOKEN_URL', default=''),
    'API_URL': config('DATACREDITO_HPN_API_URL', default=''),
    'CLIENT_ID': config('DATACREDITO_HPN_CLIENT_ID', default=''),
    'CLIENT_SECRET': config('DATACREDITO_HPN_CLIENT_SECRET', default=''),
    'USERNAME': config('DATACREDITO_HPN_USERNAME', default=''),
    'PASSWORD': config('DATACREDITO_HPN_PASSWORD', default=''),
    'USER': config('DATACREDITO_HPN_USER', default=''),
    'USER_PASSWORD': config('DATACREDITO_HPN_USER_PASSWORD', default=''),
    'PRODUCT_ID': config('DATACREDITO_HPN_PRODUCT_ID', default='64'),
    'SERVER_IP': config('DATACREDITO_HPN_SERVER_IP', default='127.0.0.1'),
}

# --- Reconocer Master API ---
DATACREDITO_RECONOCER = {
    'ENABLED': config('DATACREDITO_RECONOCER_ENABLED', default=False, cast=bool),
    'TOKEN_URL': config('DATACREDITO_RECONOCER_TOKEN_URL', default=''),
    'API_URL': config('DATACREDITO_RECONOCER_API_URL', default=''),
    'CLIENT_ID': config('DATACREDITO_RECONOCER_CLIENT_ID', default=''),
    'CLIENT_SECRET': config('DATACREDITO_RECONOCER_CLIENT_SECRET', default=''),
    'AUTHORIZATION': config('DATACREDITO_RECONOCER_AUTHORIZATION', default=''),
    'USERNAME': config('DATACREDITO_RECONOCER_USERNAME', default=''),
    'PASSWORD': config('DATACREDITO_RECONOCER_PASSWORD', default=''),
    'SCOPE': config('DATACREDITO_RECONOCER_SCOPE', default='expco_reconocer_master'),
    'NIT': config('DATACREDITO_RECONOCER_NIT', default=''),
}